#!/usr/bin/python3
"""Create a class Square"""


class Square:
    """Class square attributes
    Attributes:
    __size (int): size of a side of the square
    size=0, position=(0, 0)):
    zzzzzzzz#!/usr/bin/python3
    """Create a class Square"""


    class Square:
    """Class square attributes
    Attributes:
            
                            __size (int): size of a side of the square
                                """
                                    def __init__(self, size=0, position=(0, 0)):
                                            """initializes the square
                                                    Args:
                                                                size (int): size of a side of the square
                                                                            position (int int): The position of the square
                                                                                    Returns:
                                                                                                None
                                                                                                    """
                                                                                                            self.size = size
                                                                                                                    self.position = position

                                                                                                                        def area(self):
                                                                                                                                """calculates the square's area
                                                                                                                                        Returns:
                                                                                                                                                        The area of the square
                                                                                                                                                                """
                                                                                                                                                                        return (self.__size) ** 2

                                                                                                                                                                        @property
                                                                                                                                                                            def size(self):
                                                                                                                                                                                    """etter of __size
                                                                                                                                                                                            Returns:
                                                                                                                                                                                                        The size of the square
                                                                                                                                                                                                                """
                                                                                                                                                                                                                        return self.__size

                                                                                                                                                                                                                        @size.setter
                                                                                                                                                                                                                            def size(self, value):
                                                                                                                                                                                                                                        """setter of __size
                                                                                                                                                                                                                                                Args:
                                                                                                                                                                                                                                                            value (int): the size of a size of the square
                                                                                                                                                                                                                                                                    Returns:
                                                                                                                                                                                                                                                                                None
                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                if type(value) is not int:
                                                                                                                                                                                                                                                                                                                raise TypeError("size must be an integer")
                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                    if value < 0:
                                                                                                                                                                                                                                                                                                                                                        raise ValueError("size must be >= 0")
                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                    self.__size = value

                                                                                                                                                                                                                                                                                                                                                                                        @property
                                                                                                                                                                                                                                                                                                                                                                                            def position(self):
                                                                                                                                                                                                                                                                                                                                                                                                        """Retrieve square based on the given position"""
                                                                                                                                                                                                                                                                                                                                                                                                                return (self.__position)

                                                                                                                                                                                                                                                                                                                                                                                                                @position.setter
                                                                                                                                                                                                                                                                                                                                                                                                                    def position(self, value):
                                                                                                                                                                                                                                                                                                                                                                                                                                """Set the position of the square"""
                                                                                                                                                                                                                                                                                                                                                                                                                                        if (not isinstance(value, tuple) or
                                                                                                                                                                                                                                                                                                                                                                                                                                                        len(value) != 2 or
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        not all(isinstance(num, int) for num in value) or
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        not all(num >= 0 for num in value)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        raise TypeError("position must be a tuple of 2 positive integers")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.__position = value

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def my_print(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """prints the square with character #
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Returns:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    None
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if self.__size == 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [print("") for i in range(0, self.__position[1])]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for i in range(0, self.__size):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        [print(" ", end="") for x in range(0, self.__position[0])]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [print("#", end="") for y in range(0, self.__size)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("")"""
    initializes the square
                                                Args:
                                                            size (int): size of a side of the square
                                                                        position (int int): The position of the square
                                                                                Returns:
                                                                                            None
                                                                                                """
                                                                                                        self.size = size
                                                                                                                self.position = position

                                                                                                                    def area(self):
                                                                                                                                """calculates the square's area
                                                                                                                                        Returns:
                                                                                                                                                    The area of the square
                                                                                                                                                            """
                                                                                                                                                                    return (self.__size) ** 2

                                                                                                                                                                    @property
                                                                                                                                                                        def size(self):
                                                                                                                                                                                    """etter of __size
                                                                                                                                                                                            Returns:
                                                                                                                                                                                                        The size of the square
                                                                                                                                                                                                                """
                                                                                                                                                                                                                        return self.__size

                                                                                                                                                                                                                        @size.setter
                                                                                                                                                                                                                            def size(self, value):
                                                                                                                                                                                                                                        """setter of __size
                                                                                                                                                                                                                                                Args:
                                                                                                                                                                                                                                                            value (int): the size of a size of the square
                                                                                                                                                                                                                                                                    Returns:
                                                                                                                                                                                                                                                                                None
                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                if type(value) is not int:
                                                                                                                                                                                                                                                                                                                raise TypeError("size must be an integer")
                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                    if value < 0:
                                                                                                                                                                                                                                                                                                                                                        raise ValueError("size must be >= 0")
                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                    self.__size = value

                                                                                                                                                                                                                                                                                                                                                                                        @property
                                                                                                                                                                                                                                                                                                                                                                                            def position(self):
                                                                                                                                                                                                                                                                                                                                                                                                        """Retrieve square based on the given position"""
                                                                                                                                                                                                                                                                                                                                                                                                                return (self.__position)

                                                                                                                                                                                                                                                                                                                                                                                                                @position.setter
                                                                                                                                                                                                                                                                                                                                                                                                                    def position(self, value):
                                                                                                                                                                                                                                                                                                                                                                                                                                """Set the position of the square"""
                                                                                                                                                                                                                                                                                                                                                                                                                                        if (not isinstance(value, tuple) or
                                                                                                                                                                                                                                                                                                                                                                                                                                                                len(value) != 2 or
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                not all(isinstance(num, int) for num in value) or
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                not all(num >= 0 for num in value)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                        raise TypeError("position must be a tuple of 2 positive integers")
                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.__position = value

                                                                                                                                                                                                                                                                                                                                                                                                                                                                def my_print(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """prints the square with character #
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Returns:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                None
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if self.__size == 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [print("") for i in range(0, self.__position[1])]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for i in range(0, self.__size):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        [print(" ", end="") for x in range(0, self.__position[0])]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [print("#", end="") for y in range(0, self.__size)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("")
